version: "3.9"

services:
  ssb-room:
    image: ssbc/ssb-room2:latest
    ports: [ "4545:3000" ]
    environment:
      ROOM_PUBLISH: "false"
      ROOM_NAME: "CashuCast Dev Room"
      ROOM_HOST: "localhost"

  wt-tracker:
    image: nickert/webtorrent-tracker:latest
    command: --ws --stats
    ports: [ "8000:8000" ]

  cashu-mint:
    image: cashubtc/cashu-mint:latest
    ports: [ "3333:3333" ]
    environment:
      MINT_HOST: "0.0.0.0"
      MINT_PRIVATE_KEY: "regtestkey"
