services:
  ssb-room:
    image: staltz/ssb-room:latest
    restart: unless-stopped
    ports: [ "4545:3000" ]
    environment:
      ROOM_PUBLISH: "false"
      ROOM_NAME: "CashuCast Dev Room"
      ROOM_HOST: "localhost"

  wt-tracker:
    image: schaurian/webtorrent-hybrid:5.0.2
    command: ["sh", "-c", "npm i -g webtorrent-tracker && webtorrent-tracker --ws --stats --whitelist localhost"]
    restart: unless-stopped
    ports: [ "8000:8000" ]

  wt-seeder:
    image: node:20-alpine
    volumes: [ "torrent-cache:/cache" ]
    entrypoint: |
      sh -c "npm i -g webtorrent-cli && while true; do sleep 3600; done"
    restart: unless-stopped

  dht-bridge:
    image: anacrolix/dhttracker:latest   # UDP↔WebSocket
    restart: unless-stopped
    environment:
      ADDR: ":6881"
    networks: [internal]
    healthcheck:
      test: curl -f http://localhost:6881/debug || exit 1
      interval: 30s
      retries: 3

  cashu-mint:
    image: cashubtc/mintd:latest
    ports: [ "3333:3333" ]
    environment:
      MINT_HOST: "0.0.0.0"
      MINT_PRIVATE_KEY: "regtestkey"

volumes:
  torrent-cache:

networks:
  internal:
    internal: true
