services:
  ssb-room:
    image: staltz/ssb-room:latest
    restart: unless-stopped
    environment:
      ROOM_PUBLISH: "true"
      ROOM_NAME: "CashuCast Room"
      ROOM_HOST: "${ROOM_HOST}"

  wt-tracker:
    image: nickert/webtorrent-tracker:latest
    command:
      - webtorrent-tracker
      - --ws
      - --stats
      - --whitelist
      - cashucast.app
    restart: unless-stopped

  wt-seeder:
    image: node:20-alpine
    volumes: [ "torrent-cache:/cache" ]
    entrypoint: |
      sh -c "npm i -g webtorrent-cli && while true; do sleep 3600; done"
    restart: unless-stopped

  dht-bridge:
    image: anacrolix/dhttracker:latest   # UDP↔WebSocket
    restart: unless-stopped
    environment:
      ADDR: ":6881"
    networks: [internal]
    healthcheck:
      test: curl -f http://localhost:6881/debug || exit 1
      interval: 30s
      retries: 3

volumes:
  torrent-cache:

networks:
  internal:
    internal: true
